**As a** Developer 
**I need** An accounts list CRUD
**So that** We can keep track of the customers on your e-commerce website 
      
### Details and Assumptions
    * Database model and a Python Flask-based REST API with an endpoint to create a customer account were already developed.
    * Now we need to add the REST APIs to read, update, delete, and list accounts.
### Acceptance Criteria     
    gherkin 
    Given the developed CRUD
    When asked to create, read, update, delete or list accounts
    Then the asked task is done and an appropriate answer is sent
